/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author Jose
 */
public enum CSGeneratorProp {
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    SUBMIT_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    END_TIME_TEXT,
    START_TIME_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    INVALID_TIME_MESSAGE,
    INVALID_TIME_TITLE,
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    CHANGE_START_END_TIME_MESSAGE,
    CHANGE_START_END_TIME_TITLE, 
    //These are for Course Details Pane
    COURSE_INFO_HEADER_TEXT,
    SUBJECT_TEXT,
    NUMBER_TEXT,
    SEMESTER_TEXT,
    YEAR_TEXT,
    TITLE_TEXT,
    INSTRUCTOR_NAME_TEXT, 
    INSTRUCTOR_HOME_TEXT, 
    EXPORT_DIR_TEXT, CHANGE_BUTTON_TEXT, SITE_TEMPLATE_TEXT, SITE_TEMPLATE_DISC_TEXT, SELECT_TEMPLATE_DIR_BUTTON_TEXT, 
    SITE_PAGES_TEXT, USE_COLUMN_TEXT, NAVBAR_COLUMN_TEXT, SCRIPT_COLUMN_TEXT, FILE_COLUMN_TEXT, PAGE_STYLE_TEXT, 
    BANNER_SCHOOL_IMAGE_TEXT, LEFT_FOOTER_TEXT, RIGHT_FOOTER_TEXT, 
    STYLESHEET_TEXT,
    // THESE ARE FOR RECITATION PANE
    RECITATION_HEADER, SECTION_TEXT, INSTRUCTOR_TEXT, DAY_TIME_TEXT, LOCATION_TEXT, TA_TEXT, ADD_EDIT_HEADER, 
    SUPERVISING_TA_TEXT, 
    //These are for SchedulePane
    CALENDAR_BOUNDARIES_TEXT, STARTING_MONDAYS_TEXT, TYPE_TEXT, DATE_TEXT, TOPIC_TEXT, LINK_TEXT, CRITERIA_TEXT, ENDING_FRIDAY_TEXT, 
    SCHEDULE_ITEMS_HEADER, 
    //these are for projectPane
    COLOR_TEXT, TEXT_COLOR_TEXT, STUDENTS_HEADER, FIRST_NAME_TEXT, LAST_NAME_TEXT, TEAM_TEXT, ROLE_TEXT
    

}
